# Use official Node.js image
FROM --platform=linux/amd64 node:20 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY client/package.json client/package-lock.json ./
RUN npm install

# Copy the rest of the application files
COPY client ./

# Build the Next.js app
RUN npm run build

# Start the Next.js app
CMD ["npm", "run", "start"]
