version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVER_URL=http://server:8080
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
