# Step 1: Build the app
FROM --platform=linux/amd64 node:20 AS build

WORKDIR /app

# Install build dependencies for sqlite3 and others
RUN apk add --no-cache \
  build-base \
  python3 \
  sqlite-dev \
  bash

# Install server dependencies
COPY server/package.json server/package-lock.json ./
RUN npm install

# Rebuild sqlite3 to ensure the correct bindings for the container
RUN npm rebuild sqlite3

# Copy the rest of the server app code
COPY server/ .

# Build TypeScript files
RUN npm run build

# Expose the port your server is listening on
EXPOSE 8080

# Command to run the server
CMD ["npm", "run", "start"]
